### ISSUE TITLE
Add ability to just run deduplication for global dedpue

### ISSUE THREAD

**Issue by KONuix** [Nuix/Deduplicate-By-Profile#4]
After running the Deduplicate-By-Profile on multiple cases separately, it will be great if you can perform a global dedupe on those multiple cases without regenerating the hash again.

**Comment by JuicyDragon** [comment]
Hello @KONuix while the script had support for writing the digests to custom metadata, it didn't have any real support for later using that same value again.  I've added support for that in [v2.3.0](https://github.com/Nuix/Deduplicate-By-Profile/releases/tag/v2.3.0).

I note this in the notes for that release and the readme, but I'll re-iterate it here as well as it is valuable to see:

When **Use Existing Value if Present** is checked, the code that normally would generate the customized digest for an item during the item set creation, will look to see if the item already has a value stored in the specified custom metadata field.  If the item has a custom metadata field with the same name (as specified for setting **Digest Custom Metadata Field**) the script will further check:
- Is the value of the field non null?
- Is the value a String?
- Is the value not empty or only whitespace character?

If the value passes all of these checks, then the existing value will be used rather than generating the value from the profile.

**Care should be taken when using this setting!**  The script has no way to know if the digest value present in the field was generated by this script or using the same metadata profile!  It is very possible to run the script one time with profile A on some items and then run the script again later with profile B (or even modified profile A) and some of those same items and incompatible digests could be used!
